

const KEY='kifnet_v2';
const cats=['خوراکی','قبض','اینترنت','حمل‌ونقل','خرید','پوشاک','تفریح','سلامت','آموزش','اجاره','حقوق','فروش','هدیه','سایر'];
const themes=[['آبی','#1769ff','#0b2a5b'],['صورتی','#e74d9b','#8e245d'],['سبز','#16a36a','#075d3b'],['قرمز','#e24f52','#8f202b'],['بنفش','#7957d5','#45288e'],['نارنجی','#e98a2b','#934b0a'],['فیروزه‌ای','#149eaa','#075d66'],['سرمه‌ای','#31558f','#182d55']];
let txFilter='all';
let state=load();
function base(){return{transactions:[],budgets:[],accounts:[{id:crypto.randomUUID(),name:'کیف اصلی',type:'کیف پول',balance:0,card:''}],obligations:[],notes:'',theme:'#1769ff',mode:'light',market:{items:{},updated:null,history:[]}}}
function normalizeState(raw){const s=Object.assign(base(),raw||{});s.accounts=(Array.isArray(s.accounts)?s.accounts:[]).map(a=>({...a,id:a.id||crypto.randomUUID(),name:String(a.name||'کیف اصلی'),type:a.type||'کیف پول',balance:Number(a.balance)||0,card:a.card||''}));if(!s.accounts.length)s.accounts=base().accounts;s.transactions=(Array.isArray(s.transactions)?s.transactions:[]).map(t=>{const acc=t.accountId? s.accounts.find(a=>a.id===t.accountId):s.accounts.find(a=>a.name===t.account);return {...t,id:t.id||crypto.randomUUID(),type:['income','expense','transfer'].includes(t.type)?t.type:'expense',amount:Number(t.amount)||0,accountId:acc?.id||s.accounts[0].id,toAccountId:t.toAccountId||'',title:String(t.title||'بدون عنوان'),category:t.category||'سایر',note:t.note||'',date:t.date||new Date().toISOString()}});s.budgets=(Array.isArray(s.budgets)?s.budgets:[]).map(b=>{const acc=b.accountId?s.accounts.find(a=>a.id===b.accountId):s.accounts.find(a=>a.name===b.account);return {...b,id:b.id||crypto.randomUUID(),amount:Number(b.amount)||0,category:b.category||'',accountId:acc?.id||s.accounts[0].id,month:b.month||monthKey(new Date())}});s.market=s.market&&typeof s.market==='object'?s.market:{items:{},updated:null};s.market.items=s.market.items||{};s.market.history=Array.isArray(s.market.history)?s.market.history:[];return s}
function load(){try{return normalizeState(JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{return base()}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function fa(n){return new Intl.NumberFormat('fa-IR').format(Math.round(Number(n)||0))}
function money(n){return fa(n)+' ریال'}
function pdate(d=new Date()){return new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit',weekday:'long',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}).format(d)}
function pshort(d){return new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'2-digit',day:'2-digit',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}).format(d)}
function monthKey(d){return new Intl.DateTimeFormat('en-US',{year:'numeric',month:'2-digit',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}).format(d)}
function monthLabel(d){return new Intl.DateTimeFormat('fa-IR-u-ca-persian',{year:'numeric',month:'long',timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}).format(d)}
function ICON(n){const p={home:'<path d="m3 10 9-7 9 7v10a1 1 0 0 1-1 1h-5v-6H9v6H4a1 1 0 0 1-1-1z"/>',list:'<path d="M8 6h13M8 12h13M8 18h13M3 6h.01M3 12h.01M3 18h.01"/>',trend:'<path d="m3 17 6-6 4 4 8-9"/><path d="M17 6h4v4"/>',chart:'<path d="M4 19V5M4 19h17"/><path d="M8 16v-5M12 16V7M16 16v-8M20 16V4"/>',settings:'<path d="M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z"/><path d="m19.4 15 .1.1 1.1 1.9-2 2-1.9-1.1-.1-.1a7.7 7.7 0 0 1-2 .8l-.4 2.2h-2.8l-.4-2.2a7.7 7.7 0 0 1-2-.8l-.1.1-1.9 1.1-2-2 1.1-1.9.1-.1a7.7 7.7 0 0 1-.8-2L3.2 13V10.2l2.2-.4a7.7 7.7 0 0 1 .8-2l-.1-.1-1.1-1.9 2-2 1.9 1.1.1.1a7.7 7.7 0 0 1 2-.8l.4-2.2h2.8l.4 2.2a7.7 7.7 0 0 1 2 .8l.1-.1 1.9-1.1 2 2-1.1 1.9-.1.1a7.7 7.7 0 0 1 .8 2l2.2.4V13l-2.2.4a7.7 7.7 0 0 1-.8 1.6Z"/>',down:'<path d="M12 3v14"/><path d="m7 12 5 5 5-5"/><path d="M5 21h14"/>',up:'<path d="M12 21V7"/><path d="m7 12 5-5 5 5"/><path d="M5 3h14"/>',wallet:'<path d="M4 6h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2Z"/><path d="M16 12h6"/>',budget:'<path d="M4 6h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2Z"/><path d="M8 12h4"/><path d="M16 10v4"/>',card:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M3 10h18"/><path d="M7 15h4"/>',check:'<path d="M5 12l4 4L19 6"/><path d="M4 4h16v16H4z"/>',note:'<path d="M5 3h14v18l-4-2-3 2-3-2-4 2V3Z"/><path d="M8 8h8M8 12h6"/>',sms:'<path d="M4 5h16v11H7l-3 3V5Z"/><path d="M8 9h8M8 12h5"/>',more:'<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>'};return '<svg viewBox="0 0 24 24">'+(p[n]||p.list)+'</svg>'}
function currentMonthTotals(){const k=monthKey(new Date());return state.transactions.filter(t=>t.type!=='transfer'&&monthKey(new Date(t.date))===k).reduce((a,t)=>{a[t.type]+=Number(t.amount)||0;return a},{income:0,expense:0})}
function totalBalance(){return state.accounts.reduce((s,a)=>s+accountBalance(a),0)}
function renderClock(){const d=new Date();document.getElementById('time').textContent=new Intl.DateTimeFormat('fa-IR',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false,timeZone:Intl.DateTimeFormat().resolvedOptions().timeZone}).format(d);document.getElementById('date').textContent=pshort(d);document.getElementById('todayPersian').textContent=pdate(d)}
setInterval(renderClock,1000);renderClock();
function renderHome(){const m=currentMonthTotals();document.getElementById('totalBalance').textContent=money(totalBalance());document.getElementById('monthIncome').textContent=money(m.income);document.getElementById('monthExpense').textContent=money(m.expense);const monthBud=state.budgets.filter(b=>b.month===monthKey(new Date()));const budget=monthBud.reduce((s,b)=>s+Number(b.amount||0),0);const used=state.transactions.filter(t=>t.type==='expense'&&monthKey(new Date(t.date))===monthKey(new Date())).reduce((s,t)=>s+Number(t.amount||0),0);const p=budget?Math.min(100,Math.round(used/budget*100)):0;document.getElementById('budgetUsed').textContent=fa(p)+'٪';document.getElementById('budgetBar').style.width=p+'%';document.getElementById('budgetText').textContent=budget?money(budget):'بدون بودجه';const recent=state.transactions.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,6);document.getElementById('recentList').innerHTML=recent.length?recent.map(txHtml).join(''):'<div class="card empty">هنوز تراکنشی ثبت نشده</div>'}
function accountName(id){return state.accounts.find(a=>a.id===id)?.name||'کیف اصلی'}
function iconFor(t){return t.type==='income'?ICON('up'):t.type==='transfer'?ICON('wallet'):ICON('down')}
function txHtml(t){const acc=esc(accountName(t.accountId));const extra=t.type==='transfer'?`انتقال · ${acc} ← ${esc(accountName(t.toAccountId))}`:`${esc(t.category||'سایر')} · ${acc}`;const amountClass=t.type==='income'?'in':t.type==='transfer'?'':'out';const sign=t.type==='income'?'+':t.type==='transfer'?'↔':'−';const title=esc(t.title||'بدون عنوان');return `<div class="tx"><div class="txIcon">${iconFor(t)}</div><div class="txMain"><b>${title}</b><small>${extra} · ${pshort(new Date(t.date))}</small></div><div class="amount ${amountClass}">${sign}${money(t.amount)}</div><button class="miniAction" onclick="openTx('${t.type}','${t.id}')">ویرایش</button></div>`}
function renderTransactions(){const q=(document.getElementById('txSearch')?.value||'').trim().toLowerCase();let arr=state.transactions.filter(t=>txFilter==='all'||t.type===txFilter).filter(t=>(t.title+' '+t.category+' '+accountName(t.accountId)+' '+accountName(t.toAccountId)).toLowerCase().includes(q)).sort((a,b)=>new Date(b.date)-new Date(a.date));document.getElementById('txList').innerHTML=arr.length?arr.map(t=>txHtml(t)+`<div style="margin-top:-7px;text-align:left"><button class="chip danger" onclick="deleteTx('${t.id}')">حذف</button></div>`).join(''):'<div class="card empty">تراکنشی پیدا نشد</div>'}
function setTxFilter(f){txFilter=f;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===f));renderTransactions()}
function deleteTx(id){if(!confirm('این تراکنش حذف شود؟'))return;state.transactions=state.transactions.filter(t=>t.id!==id);save();renderAll();showToast('تراکنش حذف شد')}
function toggleTxTypeFields(kind){const category=document.getElementById('txCategoryWrap'),to=document.getElementById('txToAccountWrap'),accountLabel=document.getElementById('txAccountLabel');const transfer=kind==='transfer';if(category)category.style.display=transfer?'none':'';if(to)to.style.display=transfer?'':'none';if(accountLabel)accountLabel.textContent=transfer?'از حساب / کارت':'حساب / کارت'}
function openTx(type,id){
 type=type||'expense';
 const editing=id?state.transactions.find(t=>t.id===id):null;
 const currentType=editing?.type||type;
 const accounts=state.accounts.map(a=>`<option value="${esc(a.id)}" ${editing?.accountId===a.id?'selected':''}>${esc(a.name)}${a.card?' · '+esc(a.card):''}</option>`).join('');
 const toAccounts=state.accounts.map(a=>`<option value="${esc(a.id)}" ${editing?.toAccountId===a.id?'selected':''}>${esc(a.name)}${a.card?' · '+esc(a.card):''}</option>`).join('');
 const dt=editing?.date?new Date(editing.date):new Date();
 const local=new Date(dt.getTime()-dt.getTimezoneOffset()*60000).toISOString().slice(0,16);
 openModal(editing?(currentType==='income'?'ویرایش دخل':currentType==='transfer'?'ویرایش انتقال':'ویرایش خرج'):(currentType==='income'?'ثبت دخل':currentType==='transfer'?'ثبت انتقال':'ثبت خرج'),`<form class="form" onsubmit="submitTx(event)"><input type="hidden" name="id" value="${editing?.id||''}"><label class="label">نوع</label><select class="input" name="kind" onchange="toggleTxTypeFields(this.value)"><option value="expense" ${currentType==='expense'?'selected':''}>خرج</option><option value="income" ${currentType==='income'?'selected':''}>دخل</option><option value="transfer" ${currentType==='transfer'?'selected':''}>انتقال بین حساب‌ها</option></select><label class="label">مبلغ (ریال)</label><input class="input" name="amount" inputmode="numeric" type="number" min="1" required value="${editing?.amount||''}" placeholder="مثلاً ۵۸۸۰۰۰"><label class="label">عنوان</label><input class="input" name="title" required value="${esc(editing?.title||'')}" placeholder="مثلاً خرید اینترنت"><div id="txCategoryWrap"><label class="label">دسته‌بندی</label><select class="input" name="category">${cats.map(c=>`<option ${editing?.category===c?'selected':''}>${c}</option>`).join('')}</select></div><label class="label" id="txAccountLabel">حساب / کارت</label><select class="input" name="accountId">${accounts}</select><div id="txToAccountWrap" style="display:none"><label class="label">به حساب / کارت</label><select class="input" name="toAccountId">${toAccounts}</select></div><label class="label">تاریخ و زمان</label><input class="input" name="date" type="datetime-local" value="${local}"><label class="label">یادداشت / رسید</label><textarea class="input" name="note" rows="3" placeholder="اختیاری">${esc(editing?.note||'')}</textarea><button class="btn">${editing?'ذخیره تغییرات':'ثبت تراکنش'}</button></form>`);toggleTxTypeFields(currentType)}
function submitTx(e){e.preventDefault();const f=new FormData(e.target);const amount=Number(f.get('amount'));if(!amount||amount<1){showToast('مبلغ نامعتبر است');return}const kind=f.get('kind'),id=f.get('id'),accountId=f.get('accountId'),toAccountId=f.get('toAccountId')||'';if(!accountId||!state.accounts.some(a=>a.id===accountId)){showToast('حساب نامعتبر است');return}if(kind==='transfer'&&(!toAccountId||toAccountId===accountId)){showToast('حساب مقصد را درست انتخاب کنید');return}const item={id:id||crypto.randomUUID(),type:kind,amount,title:f.get('title'),category:f.get('category')||'سایر',accountId,toAccountId:kind==='transfer'?toAccountId:'',note:f.get('note'),date:f.get('date')?new Date(f.get('date')).toISOString():new Date().toISOString()};if(id){const i=state.transactions.findIndex(t=>t.id===id);if(i>=0)state.transactions[i]=item}else state.transactions.push(item);save();closeModal();renderAll();showToast(id?'تراکنش ویرایش شد':'تراکنش ثبت شد')}
function submitAccount(e){e.preventDefault();const f=new FormData(e.target);const id=f.get('id');const item={id:id||crypto.randomUUID(),name:f.get('name'),type:f.get('type'),balance:Number(f.get('balance'))||0,card:f.get('card')||''};if(id){const i=state.accounts.findIndex(a=>a.id===id);if(i>=0)state.accounts[i]=item}else state.accounts.push(item);save();closeModal();renderAll();showToast(id?'حساب ویرایش شد':'حساب اضافه شد')}
function accountBalance(a){let b=Number(a.balance)||0;state.transactions.forEach(t=>{const amount=Number(t.amount)||0;if(t.type==='income'&&t.accountId===a.id)b+=amount;if(t.type==='expense'&&t.accountId===a.id)b-=amount;if(t.type==='transfer'){if(t.accountId===a.id)b-=amount;if(t.toAccountId===a.id)b+=amount}});return b}
function renderAccounts(){document.getElementById('accountsList').innerHTML=state.accounts.map(a=>`<div class="accountRow"><div class="accountIcon">${ICON('card')}</div><div class="accountInfo"><b>${esc(a.name)}</b><small>${esc(a.type)}${a.card?' · **** '+esc(a.card):''}</small></div><div><strong>${money(accountBalance(a))}</strong><div class="accountActions"><button class="chip" onclick="openAccount('${a.id}')">ویرایش</button></div></div></div>`).join('')}
function openAccount(id){const editing=id?state.accounts.find(a=>a.id===id):null;openModal(editing?'ویرایش حساب / کارت':'حساب / کارت',`<form class="form" onsubmit="submitAccount(event)"><input type="hidden" name="id" value="${editing?.id||''}"><label class="label">نام بانک / حساب</label><input class="input" name="name" required value="${esc(editing?.name||'')}" placeholder="مثلاً سامان"><label class="label">نوع</label><select class="input" name="type">${['حساب بانکی','کارت','کیف پول','نقدی'].map(x=>`<option ${editing?.type===x?'selected':''}>${x}</option>`).join('')}</select><label class="label">موجودی اولیه (ریال)</label><input class="input" name="balance" type="number" value="${editing?.balance??0}"><label class="label">۴ رقم آخر کارت</label><input class="input" name="card" inputmode="numeric" maxlength="4" value="${esc(editing?.card||'')}" placeholder="اختیاری"><button class="btn">${editing?'ذخیره تغییرات':'ثبت'}</button></form>`)}
function openBudget(){openModal('بودجه',`<form class="form" onsubmit="submitBudget(event)"><label class="label">مبلغ بودجه (ریال)</label><input class="input" name="amount" type="number" min="0" required><label class="label">دسته‌بندی</label><select class="input" name="category"><option value="">کل هزینه‌ها</option>${cats.map(c=>`<option>${c}</option>`).join('')}</select><label class="label">حساب</label><select class="input" name="accountId">${state.accounts.map(a=>`<option value="${esc(a.id)}">${esc(a.name)}</option>`).join('')}</select><button class="btn">ثبت بودجه</button></form>`)}
function submitBudget(e){e.preventDefault();const f=new FormData(e.target);const accountId=f.get('accountId');if(!state.accounts.some(a=>a.id===accountId)){showToast('حساب نامعتبر است');return}state.budgets.push({id:crypto.randomUUID(),amount:Number(f.get('amount'))||0,category:f.get('category'),accountId,month:monthKey(new Date())});save();closeModal();renderAll();showToast('بودجه ثبت شد')}
function renderBudget(){const el=document.getElementById('budgetList');if(!state.budgets.length){el.innerHTML='<div class="card empty">بودجه‌ای ثبت نشده</div>';return}el.innerHTML=state.budgets.slice().reverse().map(b=>{const spent=state.transactions.filter(t=>t.type==='expense'&&t.accountId===b.accountId&&monthKey(new Date(t.date))===b.month&&(!b.category||t.category===b.category)).reduce((s,t)=>s+Number(t.amount),0);const p=b.amount?Math.min(100,Math.round(spent/b.amount*100)):0;return `<div class="card"><div class="sectionHead" style="margin:0 0 8px"><div><b>${esc(b.category||'کل هزینه‌ها')}</b><small class="muted" style="display:block">${esc(accountName(b.accountId))}</small></div><strong>${money(b.amount)}</strong></div><div class="bar"><span style="width:${p}%;${p>=90?'background:var(--out)':''}"></span></div><div class="sectionHead" style="margin:8px 0 0"><small class="muted">مصرف ${money(spent)}</small><button class="chip danger" onclick="deleteBudget('${b.id}')">حذف</button></div></div>`}).join('')}
function deleteBudget(id){state.budgets=state.budgets.filter(b=>b.id!==id);save();renderAll()}
function monthTotals(d){const k=monthKey(d);return state.transactions.filter(t=>t.type!=='transfer'&&monthKey(new Date(t.date))===k).reduce((a,t)=>{a[t.type]+=Number(t.amount)||0;return a},{income:0,expense:0})}
function renderReports(){const m=currentMonthTotals();document.getElementById('rIncome').textContent=money(m.income);document.getElementById('rExpense').textContent=money(m.expense);document.getElementById('rNet').textContent=money(m.income-m.expense);const months=[];for(let i=0;i<6;i++){const d=new Date();d.setMonth(d.getMonth()-i);months.push({d,...monthTotals(d)})}const maxE=Math.max(...months.map(x=>x.expense),1);document.getElementById('monthCompare').innerHTML=months.map(x=>`<div class="chartRow"><div class="chartMeta"><span>${monthLabel(x.d)}</span><b>${money(x.expense)}</b></div><div class="bar"><span style="width:${Math.round(x.expense/maxE*100)}%"></span></div><small class="muted">دخل ${money(x.income)}</small></div>`).join('');const catsMap={};state.transactions.filter(t=>t.type==='expense').forEach(t=>catsMap[t.category]=(catsMap[t.category]||0)+Number(t.amount));const maxC=Math.max(...Object.values(catsMap),1);document.getElementById('catReport').innerHTML=Object.entries(catsMap).sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k,v])=>`<div class="chartRow"><div class="chartMeta"><span>${esc(k)}</span><b>${money(v)}</b></div><div class="bar"><span style="width:${Math.round(v/maxC*100)}%"></span></div></div>`).join('')||'<div class="empty">داده‌ای وجود ندارد</div>';const maxV=Math.max(...months.flatMap(x=>[x.income,x.expense]),1);document.getElementById('trend').innerHTML=months.slice().reverse().map(x=>`<div class="chartRow"><div class="chartMeta"><span>${monthLabel(x.d)}</span><span>دخل ${money(x.income)} · خرج ${money(x.expense)}</span></div><div class="bar"><span style="width:${Math.round(x.income/maxV*100)}%;background:var(--in)"></span></div><div class="bar" style="margin-top:5px"><span style="width:${Math.round(x.expense/maxV*100)}%;background:var(--out)"></span></div></div>`).join('');document.getElementById('reportTable').innerHTML=state.transactions.slice().sort((a,b)=>new Date(b.date)-new Date(a.date)).map(t=>`<tr><td>${esc(t.title)}</td><td>${t.type==='income'?'دخل':'خرج'}</td><td>${esc(t.category)}</td><td>${money(t.amount)}</td><td>${pshort(new Date(t.date))}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">داده‌ای وجود ندارد</td></tr>'}
function exportExcel(){const rows=[['عنوان','نوع','دسته‌بندی','مبلغ ریال','حساب','حساب مقصد','تاریخ','یادداشت'],...state.transactions.map(t=>[t.title,t.type==='income'?'دخل':t.type==='transfer'?'انتقال':'خرج',t.category||'',t.amount,accountName(t.accountId),accountName(t.toAccountId),pshort(new Date(t.date)),t.note||''])];const csv='\ufeff'+rows.map(r=>r.map(x=>'"'+String(x??'').replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='kifnet-transactions.csv';a.click();showToast('فایل CSV آماده شد')}
function printReport(){showView('reports');setTimeout(()=>window.print(),100)}
function renderObligations(){document.getElementById('obligationsList').innerHTML=state.obligations.length?state.obligations.slice().sort((a,b)=>a.due.localeCompare(b.due)).map(o=>`<div class="card"><div class="sectionHead" style="margin:0"><div><b>${esc(o.title)}</b><small>${esc(o.kind)} · ${esc(o.due)}</small></div><strong>${money(o.amount)}</strong></div></div>`).join(''):'<div class="card empty">موردی ثبت نشده</div>'}
function openObligation(){openModal('چک / قسط',`<form class="form" onsubmit="submitObligation(event)"><label class="label">عنوان</label><input class="input" name="title" required placeholder="مثلاً قسط خودرو"><label class="label">نوع</label><select class="input" name="kind"><option>قسط</option><option>چک</option><option>وام</option></select><label class="label">مبلغ (ریال)</label><input class="input" name="amount" type="number" required><label class="label">سررسید</label><input class="input" name="due" type="date" required><button class="btn">ثبت</button></form>`)}
function submitObligation(e){e.preventDefault();const f=new FormData(e.target);state.obligations.push({id:crypto.randomUUID(),title:f.get('title'),kind:f.get('kind'),amount:Number(f.get('amount')),due:f.get('due')});save();closeModal();renderObligations();showToast('ثبت شد')}
function renderNotes(){document.getElementById('notesInput').value=state.notes||''}
function saveNotes(){state.notes=document.getElementById('notesInput').value;save();showToast('ذخیره شد')}
function backupData(){const payload={...state,backupVersion:7,backupAt:new Date().toISOString()};const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'}));a.download='kifnet-backup-v7.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);showToast('فایل پشتیبان آماده شد')}
function restoreData(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const imported=normalizeState(JSON.parse(reader.result));if(!confirm('داده‌های فعلی با این فایل پشتیبان جایگزین شود؟'))return;state=imported;save();renderAll();showToast('پشتیبان بازیابی شد')}catch{showToast('فایل پشتیبان نامعتبر است')}finally{e.target.value=''}};reader.readAsText(file)}
function renderThemes(){document.getElementById('themes').innerHTML=themes.map(t=>`<button class="theme ${state.theme===t[1]?'selected':''}" style="background:${t[1]}" onclick="setTheme('${t[1]}')">${t[0]}</button>`).join('');document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode))}
function themePair(c){const t=themes.find(x=>x[1]===c);return t||themes[0]}
function applyTheme(){const t=themePair(state.theme);document.documentElement.style.setProperty('--p',t[1]);document.documentElement.style.setProperty('--p2',t[2]);const dark=state.mode==='dark'||(state.mode==='system'&&matchMedia('(prefers-color-scheme:dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';document.querySelector('meta[name=theme-color]')?.setAttribute('content',dark?'#0b2a5b':t[1]);const splash=document.getElementById('splash');if(splash)splash.classList.toggle('darkMode',dark)}
function setMode(m){state.mode=m;save();applyTheme();renderThemes()}
function setTheme(c){state.theme=c;save();applyTheme();renderThemes();renderHome()}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='home')renderHome();if(id==='transactions')renderTransactions();if(id==='budget')renderBudget();if(id==='reports')renderReports();if(id==='more'){}if(id==='market')renderMarket();if(id==='accounts')renderAccounts();if(id==='obligations')renderObligations();if(id==='notes')renderNotes();if(id==='settings')renderThemes()}
function openModal(title,body){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=body;document.getElementById('modal').classList.add('open')}
function closeModal(){document.getElementById('modal').classList.remove('open')}
function showToast(s){const e=document.getElementById('toast');e.textContent=s;e.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.classList.remove('show'),2300)}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function resetData(){if(confirm('همه داده‌های کیف‌نت پاک شود؟')){localStorage.removeItem(KEY);state=load();renderAll();showToast('داده‌ها پاک شد')}}
function openSms(){openModal('پیامک بانکی',`<form class="form" onsubmit="parseSms(event)"><textarea class="input" name="sms" rows="7" required placeholder="متن پیامک بانکی…"></textarea><button class="btn">ثبت از روی پیامک</button></form>`)}
function parseSms(e){e.preventDefault();const text=String(new FormData(e.target).get('sms')||'');const clean=normalizeDigits(text).replace(/\u200c/g,' ').replace(/[,٬،]/g,'').replace(/\s+/g,' ');const income=/واریز|دریافت|بستانکار|واریزی|شارژ حساب/i.test(clean);const expense=/برداشت|خرید|پرداخت|بدهکار|خروج/i.test(clean);const type=income&&!expense?'income':expense&&!income?'expense':income?'income':'expense';const patterns=[/(?:مبلغ|مبلغ تراکنش|مبلغ واریز|مبلغ برداشت|مبلغ خرید)\D{0,30}(\d{4,})/i,/(?:واریز|برداشت|خرید|پرداخت|دریافت)\D{0,25}(\d{4,})/i,/(\d{4,})\s*(?:ریال|تومان)/i];let amount=0;for(const r of patterns){const m=r.exec(clean);if(m){amount=Number(m[1]);break}}if(!amount){const nums=clean.match(/\d{4,}/g)||[];const candidates=nums.filter(n=>!/^\d{4}$/.test(n)&&!/^(?:6037|5892|6274|6104|6219|5022|5058|5041|6367|5029|6273|6280)/.test(n));amount=Number(candidates[0]||0)}if(!amount){showToast('مبلغی از پیامک پیدا نشد');return}const unit=/تومان/i.test(clean)&&!/ریال/i.test(clean)?10:1;amount*=unit;state.transactions.push({id:crypto.randomUUID(),type,amount,title:'تراکنش پیامکی',category:'سایر',accountId:state.accounts[0]?.id||'',toAccountId:'',note:text,date:new Date().toISOString()});save();closeModal();renderAll();showToast('تراکنش پیامکی ثبت شد')}
function normalizeDigits(s){return String(s).replace(/[۰-۹]/g,d=>'۰۱۲۳۴۵۶۷۸۹'.indexOf(d)).replace(/[,٬،٫]/g,'')}
function cleanMarketText(text){try{return new DOMParser().parseFromString(text,'text/html').body.innerText.replace(/\u200c/g,' ').replace(/\s+/g,' ').trim()}catch{return String(text).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}}
function extractNumberAfter(text,labels){for(const label of labels){const r=new RegExp(label+'[^0-9]{0,80}([0-9]{1,3}(?:[ ,]+[0-9]{3})+|[0-9]{5,})(?:\\s*(?:تومان|ریال|\\$))?','i').exec(text);if(r)return Number(r[1].replace(/[ ,]/g,''))}return 0}
function extractCurrency(text,labels){for(const label of labels){const r=new RegExp(label+'\\s+([0-9]{1,3}(?:,[0-9]{3})+|[0-9]{4,})\\s+([0-9]{1,3}(?:,[0-9]{3})+|[0-9]{4,})','i').exec(text);if(r)return{buy:Number(r[1].replace(/,/g,'')),sell:Number(r[2].replace(/,/g,''))}}return null}
function parseMarketText(text){const clean=cleanMarketText(normalizeDigits(text));const items={};const goldLabels={gold18:['گرم طلای 18 عیار','گرم طلای 18','طلای 18 عیار'],mesghal:['آبشده\\(مثقال طلا\\)','مظنه','آبشده'],newCoin:['سکه امامی \\(طرح جدید\\)','سکه امامی'],oldCoin:['سکه بهار آزادی'],half:['نیم سکه'],quarter:['ربع سکه'],gerami:['سکه گرمی'],ounce:['انس طلا']};for(const [k,labels] of Object.entries(goldLabels)){const v=extractNumberAfter(clean,labels);if(v)items[k]=v}const currencies={usd:['دلار آمریکا'],eur:['یورو'],aed:['درهم'],try:['لیر ترکیه'],gbp:['پوند انگلیس'],cny:['یوان چین'],cad:['دلار کانادا'],aud:['دلار استرالیا'],rub:['روبل روسیه']};for(const [k,labels] of Object.entries(currencies)){const v=extractCurrency(clean,labels);if(v)items[k]=v}return items}
let marketBusy=false,marketTimer=null,pulsePeriod='live';
async function fetchText(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw Error('fetch');return await r.text()}
async function fetchSource(url){try{return await fetchText(url+'?kifnet='+Date.now())}catch(e){return await fetchText('https://r.jina.ai/http://'+url.replace(/^https?:\/\//,'' )+'?kifnet='+Date.now())}}
function numericMarketValue(v){return typeof v==='object'?(Number(v.sell)||Number(v.buy)||0):Number(v)||0}
function addMarketSnapshot(items){const wanted=['newCoin','gold24','usd'];const values={};wanted.forEach(k=>{const v=items[k];if(v!=null){const n=numericMarketValue(v);if(n>0)values[k]=n}});if(Object.keys(values).length<2)return;const now=Date.now();const h=state.market.history||[];const last=h[h.length-1];if(last&&now-last.t<25000)return;h.push({t:now,...values});const cutoff=now-366*86400000;state.market.history=h.filter(x=>x.t>=cutoff);save()}
async function refreshMarket(silent=false){if(marketBusy)return;marketBusy=true;if(!silent)showToast('در حال بروزرسانی…');const sources=['https://alanchand.com/','https://www.estjt.ir/price/'];let merged={},ok=false;for(const url of sources){try{const text=await fetchSource(url);const x=parseMarketText(text);if(Object.keys(x).length){merged={...merged,...x};ok=true}}catch(e){}}if(ok){const prev=state.market.items||{};state.market.prev={...prev};state.market.items={...prev,...merged};state.market.updated=new Date().toISOString();state.market.source='الان‌چند / اتحادیه طلا و جواهر تهران';addMarketSnapshot(state.market.items);renderMarket();if(document.getElementById('marketPulseModal')?.classList.contains('open'))renderPulse();if(!silent)showToast('بازار بروزرسانی شد')}else if(!silent){renderMarket();showToast('اتصال بازار در دسترس نیست')}marketBusy=false}
function marketRow(name,key,unit,kind='gold'){const m=state.market.items||{},v=m[key];if(!v)return `<tr><td class="marketName">${name}</td><td>—</td><td>—</td><td>${unit}</td><td class="marketChange flat">—</td></tr>`;const buy=typeof v==='object'?v.buy:v,sell=typeof v==='object'?v.sell:v;const old=state.market.prev?.[key];const current=typeof v==='object'?v.sell:v;const oldVal=old?numericMarketValue(old):0;const diff=Number(current)-oldVal;const pct=oldVal?((diff/oldVal)*100):0;const cls=diff>0?'up':diff<0?'down':'flat';return `<tr><td class="marketName">${name}</td><td>${fa(buy)}</td><td>${fa(sell)}</td><td>${unit}</td><td class="marketChange ${cls}">${oldVal?(diff>0?'▲ ':diff<0?'▼ ':'')+Math.abs(pct).toFixed(2)+'٪':'—'}</td></tr>`}
function renderMarket(){const el=document.getElementById('marketGrid');if(!el)return;const rows=[['گرم طلای ۱۸ عیار','gold18','تومان'],['گرم طلای ۲۴ عیار','gold24','تومان'],['آبشده (مثقال)','mesghal','تومان'],['سکه تمام بهار آزادی','newCoin','تومان'],['سکه امامی (طرح جدید)','newCoin','تومان'],['سکه بهار آزادی (طرح قدیم)','oldCoin','تومان'],['نیم سکه','half','تومان'],['ربع سکه','quarter','تومان'],['سکه گرمی','gerami','تومان'],['انس طلا','ounce','$'],['دلار آمریکا','usd','تومان'],['یورو','eur','تومان'],['درهم','aed','تومان'],['لیر ترکیه','try','تومان'],['پوند انگلیس','gbp','تومان'],['یوان چین','cny','تومان']];el.innerHTML=rows.map(r=>marketRow(...r)).join('');const updated=document.getElementById('marketUpdated');if(updated)updated.textContent=state.market.updated?new Date(state.market.updated).toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';const status=document.getElementById('marketStatus');if(status)status.textContent=state.market.updated?'زنده · بروزرسانی دوره‌ای':'در انتظار نرخ زنده'}
function openMarketPulse(){document.getElementById('marketPulseModal')?.classList.add('open');document.getElementById('marketPulseModal')?.setAttribute('aria-hidden','false');renderPulse()}
function closeMarketPulse(){document.getElementById('marketPulseModal')?.classList.remove('open');document.getElementById('marketPulseModal')?.setAttribute('aria-hidden','true')}
function setPulsePeriod(period){pulsePeriod=period;document.querySelectorAll('.pulseTabs .chip').forEach(b=>b.classList.toggle('active',b.dataset.period===period));renderPulse()}
function pulseWindow(period){const now=Date.now();return period==='live'?now-6*3600000:period==='week'?now-7*86400000:period==='month'?now-30*86400000:now-365*86400000}
function pulseLabel(ts,period){const d=new Date(ts);if(period==='live')return d.toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'});if(period==='year')return d.toLocaleDateString('fa-IR',{month:'short'});return d.toLocaleDateString('fa-IR',{month:'2-digit',day:'2-digit'})}
function drawPulseChart(canvas,data,key,period){const rect=canvas.getBoundingClientRect(),dpr=Math.max(1,devicePixelRatio||1),w=Math.max(280,rect.width),h=190;canvas.width=w*dpr;canvas.height=h*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const vals=data.map(x=>Number(x[key])).filter(Number.isFinite);if(!vals.length){c.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--muted');c.font='12px Vazirmatn';c.textAlign='center';c.fillText('هنوز داده کافی ثبت نشده است',w/2,h/2);return}const min=Math.min(...vals),max=Math.max(...vals),range=Math.max(1,max-min),pad={l:8,r:8,t:18,b:28};const x=i=>pad.l+(i/(Math.max(1,data.length-1)))*(w-pad.l-pad.r),y=v=>pad.t+(1-(v-min)/range)*(h-pad.t-pad.b);const line=getComputedStyle(document.documentElement).getPropertyValue('--p').trim()||'#1769ff',grid=getComputedStyle(document.documentElement).getPropertyValue('--line').trim(),muted=getComputedStyle(document.documentElement).getPropertyValue('--muted').trim(),text=getComputedStyle(document.documentElement).getPropertyValue('--text').trim();c.strokeStyle=grid;c.lineWidth=1;for(let i=0;i<4;i++){const yy=pad.t+i*(h-pad.t-pad.b)/3;c.beginPath();c.moveTo(pad.l,yy);c.lineTo(w-pad.r,yy);c.stroke()}const grad=c.createLinearGradient(0,pad.t,0,h);grad.addColorStop(0,line+'35');grad.addColorStop(1,line+'00');c.beginPath();data.forEach((p,i)=>{const xx=x(i),yy=y(p[key]);i?c.lineTo(xx,yy):c.moveTo(xx,yy)});c.lineTo(x(data.length-1),h-pad.b);c.lineTo(x(0),h-pad.b);c.closePath();c.fillStyle=grad;c.fill();c.beginPath();data.forEach((p,i)=>{const xx=x(i),yy=y(p[key]);i?c.lineTo(xx,yy):c.moveTo(xx,yy)});c.strokeStyle=line;c.lineWidth=2.5;c.stroke();c.fillStyle=muted;c.font='10px Vazirmatn';c.textAlign='right';c.fillText(fa(max),w-8,12);c.fillText(fa(min),w-8,h-6);c.textAlign='left';if(data.length)c.fillText(pulseLabel(data[0].t,period),8,h-6);c.textAlign='right';if(data.length>1)c.fillText(pulseLabel(data[data.length-1].t,period),w-8,h-6);c.fillStyle=text;c.font='bold 11px Vazirmatn';c.textAlign='left';c.fillText('تومان',8,14)}
function pulseSeries(){const from=pulseWindow(pulsePeriod),raw=(state.market.history||[]).filter(x=>x.t>=from).sort((a,b)=>a.t-b.t);if(raw.length<2)return raw;const bucket=pulsePeriod==='live'?60000:pulsePeriod==='week'?3600000:pulsePeriod==='month'?6*3600000:86400000;const out=[];let lastBucket=-1;raw.forEach(x=>{const b=Math.floor(x.t/bucket);if(b!==lastBucket){out.push(x);lastBucket=b}});return out}
function renderPulse(){const charts=document.getElementById('pulseCharts');if(!charts)return;const data=pulseSeries(),defs=[['newCoin','سکه تمام بهار آزادی'],['gold24','طلای ۲۴ عیار'],['usd','دلار آمریکا']];charts.innerHTML=defs.map(([key,title])=>`<div class="pulseChart card"><div class="pulseChartHead"><b>${title}</b><span>${data.length?fa(data[data.length-1][key]||0):'—'} تومان</span></div><canvas id="pulse_${key}"></canvas></div>`).join('');defs.forEach(([key])=>{const cv=document.getElementById('pulse_'+key);if(cv)drawPulseChart(cv,data,key,pulsePeriod)});const u=document.getElementById('pulseUpdated');if(u)u.textContent=state.market.updated?'آخرین نرخ: '+new Date(state.market.updated).toLocaleTimeString('fa-IR'):'بدون داده';const hint=document.getElementById('pulseHint');if(hint)hint.textContent=data.length>1?'نمودار بر اساس داده‌هایی است که کیف‌نت از زمان فعال بودن بازار روی همین دستگاه ثبت کرده است.':'برای نمایش روند، بازار را باز بگذارید تا نمونه‌های قیمت ثبت شوند.'}
function renderAll(){applyTheme();renderThemes();renderHome();renderTransactions();renderBudget();renderReports();renderAccounts();renderObligations();renderNotes();renderMarket()}
renderAll();
setTimeout(()=>refreshMarket(true),250);
window.addEventListener('load',()=>{setTimeout(()=>document.getElementById('splash')?.classList.add('hide'),1500)});
if('serviceWorker' in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
window.addEventListener('storage',()=>{state=load();renderAll()});
marketTimer=setInterval(()=>{if(document.getElementById('market')?.classList.contains('active'))refreshMarket(true)},30000);
window.addEventListener('resize',()=>{if(document.getElementById('marketPulseModal')?.classList.contains('open'))renderPulse()});

